### ISSUE TITLE
user define path

### ISSUE THREAD

**Issue by frank0434** [femiguez/apsimx#1]
Hi @femiguez 

It is great to have an r pkg for apsim/apsimx. 

Just wondering if you are going to add the feature to allow a user-defined path to where the apsimx installed? Like your note in the `apsimx.R`
https://github.com/femiguez/apsimx/blob/c4aa97882e5f0c3a73709c3676652a26c6860472/R/apsimx.R#L416-L419

I tried to set the `apsimx_options` manually. 
The function will trigger the apsimx UI, but still reports the same error message. 
and in the UI, it says **Cannot read file: .\Maize.apsimx. File does not exist.**
```
> maize <- apsimx_example("Maize")
Error in read_apsimx(paste0(example, ".db"), value = "report") : 
  There are no .db files in the specified directory to read.
In addition: Warning message:
In file.copy(from = ex, to = ".", copy.mode = FALSE) :
  problem copying "c:\Data\ApsimX\Examples\"\Maize.apsimx to .\Maize.apsimx: Invalid argument
```
I think it might be because the `file.copy` rule in functions?
https://github.com/femiguez/apsimx/blob/c4aa97882e5f0c3a73709c3676652a26c6860472/R/apsimx.R#L292

I assume that the current pkg is only working for the stable release? 
I am using a custom build version, which only shows the version number if I run the `Models /Version` call in the `shell`.

**Comment by femiguez** [comment]
Hi Frank, Thanks for your interest in the package. I suspect that the problem is that you have APSIM installed in an alternative location and you have correctly set that using 'apsimx_options', but then you also need to set the path to the examples folder manually.

**Comment by femiguez** [comment]
Thanks Frank! This was an error and it is now fixed in the current version of the package 0.85

**Comment by frank0434** [comment]
thanks @femiguez. will give it go. close it now.

**Comment by femiguez** [comment]
Thanks Frank! I do not have your system/setup to test this, but I believe I
fixed the problem, so I need your confirmation that it actually works. Note
that the bug did not affect your ability to run apsimx, it only affected
the ability to find the 'Examples' folder.
