### ISSUE TITLE
Soil profiles from SoilGrids often have unacceptable saturation

### ISSUE THREAD

**Issue by femiguez** [femiguez/apsimx#100]
APSIM Next Gen rejects the soils as produced by SoilGrids. The solution might be to add a function called 'fix_apsimx_soil_profile' that can check for this and correct it so that it passes the APSIM Next Gen checks.

This issue was reported by Julien Morel

**Comment by femiguez** [comment]
This might be fixed now

**Comment by gabrielhintz** [comment]
@femiguez 

This function is not available such as its package "apsimr".

**Comment by femiguez** [comment]
I'm not sure I understand this question or comment. The version of the package in github has fixed this. There is an argument 'fix' which is FALSE by default, but change it to TRUE and soils should be fine.
The package 'apsimr' has been deprecated.

**Comment by gabrielhintz** [comment]
Thank you @femiguez.
