### ISSUE TITLE
Changing the weather file through R

### ISSUE THREAD

**Issue by harsh-pathak-purdue** [femiguez/apsimx#108]
Greetings all,

Does the following capture your interest, then please proceed,
Please note that I was trying to replace the weather data coming from the NASA POWER in the original simulation with the data coming through Mesonet, using R

This was the code that I wrote for fetching the weather data
`weather_data <-get_iem_apsim_met(lonlat = c(lon, lat), dates = c("YYYY-MM-DD", "YYYY-MM-DD"))
summary(weather_data)
`
and this was the code that I was using to replace the original weather data, which in the end, didn't work.
`
edit_apsimx_replacement("v1-edited.apsimx", src.dir = source.path,
             wrt.dir = write.path, node = "Weather",
            value = weather_data)
`

I would appreciate your suggestions, time, and comments.

**Comment by femiguez** [comment]
Can you attach the apsimx file? It would be easier for me to help you. Instead of 'weather_data' you need to use the name of the file. For example, 'NASA-POWER-XXX.met'.
