### ISSUE TITLE
There are no .db files in the specified directory to read error

### ISSUE THREAD

**Issue by megpaiop** [femiguez/apsimx#109]
Hi,
I am using Colab to run APSIM.
I installed APSIM latest version:
2023.1.7136.0
And apsimx.
When I try this commands to check if everything is ok:
ex.dir <- auto_detect_apsimx_examples()
## (or change as needed)
tmp.dir2 <- tempdir()
file.copy(paste0(ex.dir, "/", "Wheat.apsimx"), tmp.dir2)
sim <- apsimx("Wheat.apsimx", src.dir = tmp.dir2, value = "report")

I get the error:
"There are no .db files in the specified directory to read error"

Any idea how to resolve this error?

**Comment by femiguez** [comment]
It would be helpful to know what 'ex.dir' points to. Can you first try:

```
sim <- apsimx("Wheat.apsimx", src.dir = tmp.dir2)
```

Also, show the output of 

```
dir(path = tmp.dir2)
```

**Comment by femiguez** [comment]
I will close this unless you have other questions
