### ISSUE TITLE
Using APSIM Next Generation through R

### ISSUE THREAD

**Issue by harsh-pathak-purdue** [femiguez/apsimx#110]
Greetings all,

If this captures your interest, then please proceed!

I am trying to change the GUI values in APSIM next generation for sowing date, seed rate, and plant population using R by using the edit_apsimx() function. Using the following function shows results on R console but checking back the GUI of APSIM next generation, I still see the default value. I will appreciate your suggestions and advice.
Code for changing plant population with a value = 9
`edit_apsimx("filename.apsimx",src.dir = src.path, wrt.dir = wrt.path, node = "Manager", manager.child = "Sow on a fixed date", parm = "Plant population", value = value) `

Result in R console is:
![image](https://user-images.githubusercontent.com/89477883/217084931-110c3346-2607-49e1-b6e2-c243f0d384c1.png)

Result on GUI
![image](https://user-images.githubusercontent.com/89477883/217085485-57d3741a-bd73-45f6-a0fd-38536ed02d5f.png)

Thanks

**Comment by femiguez** [comment]
Can you attach the apsimx file to the message? It will be easier for me to help you

**Comment by harsh-pathak-purdue** [comment]
The sample apsim file is inside the zip folder, which was provided during the training time at Iowa State. 
[optimum_N_rate.zip](https://github.com/femiguez/apsimx/files/10670338/optimum_N_rate.zip)

Please note that before changing the "Sow on a fixed date" parameters, I used edit_apsimx() function to change the start and end date of the simulation and weather file using R, which worked well.

**Comment by femiguez** [comment]
@harsh-pathak-purdue I'm attaching an R file that can edit the parameter Population. Let me know if you have other questions

[edit_optimum_N_rate.r.zip](https://github.com/femiguez/apsimx/files/10698141/edit_optimum_N_rate.r.zip)

**Comment by femiguez** [comment]
I will close this unless you have other questions

**Comment by harsh-pathak-purdue** [comment]
Thanks for the help
