### ISSUE TITLE
New Cultivars

### ISSUE THREAD

**Issue by Janewanguimugo** [femiguez/apsimx#111]
Is it possible to edit for example  _: [Phenology].Vegetative.Target.FixedValue = 328_  and create a new cultivar using R?

**CODE**
tmp.dir <- tempdir()
extd.dir <- system.file("extdata", package = "apsimx")
inspect_apsimx_replacement("MaizeSoybean.apsimx", 
                           src.dir = extd.dir,
                           node = "Soybean", 
                           node.child = "Cultivars",
                           node.subchild = "USA",
                           node.subsubchild = "PioneerP22T61_MG22",
                           display.available = FALSE)

**RESULT**
Replacements:  Maize Soybean 
node: Soybean 
node child: Cultivars 
node subchild: USA 
Subchild Name:  USA 
Name sub-sub-child:  PioneerP22T61_MG22 
$type : Models.PMF.Cultivar, Models 
 : [Phenology].Vegetative.Target.FixedValue = 328 
 : [Phenology].EarlyFlowering.Target.FixedValue = 106 
 : [Phenology].EarlyGrainFilling.Target.FractionofGrainfilling.FixedValue = 0.3 
 : [Phenology].LateGrainFilling.Target.EntireGrainfillPeriod.FixedValue = 499 
 : [Phenology].VegetativePhotoperiodModifier.XYPairs.X = 13.59, 17.6 
 : [Phenology].ReproductivePhotoperiodModifier.XYPairs.X = 13.59, 17.6

**Comment by Janewanguimugo** [comment]
I have four new varieties in the file attached...I would appreciate how to edit them in R. Thank you
[cultivar.zip](https://github.com/femiguez/apsimx/files/10682126/cultivar.zip)

**Comment by femiguez** [comment]
This script edits the cultivars (one example) as you have them in your file. I'm not sure that this will work in general as we normally use replacements to create and modify cultivars.

[edit_soybean_cultivars.r.zip](https://github.com/femiguez/apsimx/files/10698376/edit_soybean_cultivars.r.zip)

**Comment by Janewanguimugo** [comment]
Thank you so much

**Comment by Janewanguimugo** [comment]
It didn't work...

**Comment by femiguez** [comment]
@Janewanguimugo it should be 'overwrite' instead of 'overwite'

**Comment by femiguez** [comment]
@Janewanguimugo I'm closing this, but feel free to open a new issue if you have questions
