### ISSUE TITLE
Error editing Soil Physical Parameters with apsimx

### ISSUE THREAD

**Issue by hugowinkfield** [femiguez/apsimx#115]
Hi, 

I am having a problem editing Soil Physical Parameters with apsimx. When I run edit_apsimx with the following code:

`edit_apsimx("Ecosystem_Services2.apsimx",
            src.dir = Model_location,
            wrt.dir = Model_location,
            node = "Soil",
            soil.child = "Physical",
            parm = "BD"
            value = c(SoilData$BD[i], (SoilData$BD[i] * 1.03))
            )`

Where the values are taken from a large spatial dataset and the code is run in a for loop.

The returned error message is:

`Error in if (soil.water.node$Name != "Water" && soil.water.node$Name !=  : 
  missing value where TRUE/FALSE needed`

Here is my Zipped Apsim File:
[Ecosystem_Services2.zip](https://github.com/femiguez/apsimx/files/10759345/Ecosystem_Services2.zip)

Thanks very much for your help

-A stressed undergrad student!

**Comment by femiguez** [comment]
I do not recommend building a soil profile in APSIM with just two layers. See this reference for help with building APSIM soil profiles

[Richota-APSIM-Soil.pdf.zip](https://github.com/femiguez/apsimx/files/10808484/Richota-APSIM-Soil.pdf.zip)

To edit the file try this:

```
pp1 <- inspect_apsimx("Ecosystem_Services2.apsimx",
                      node = "Soil",
                      soil.child = "Physical",
                      parm = "BD",
                      print.path = TRUE)

edit_apsimx("Ecosystem_Services2.apsimx",
             node = "Other",
             parm.path = pp1,
             value = c(1.4, 1.4))
```

**Comment by hugowinkfield** [comment]
Hi

Thanks for your advice. I have tried using that but the same error comes
up. It works now if I replace the entire soil profile, though.


Kind regards
Hugo

**Comment by femiguez** [comment]
@hugowinkfield I don't know why it does not work for you. What version of the apsimx package are you using? Maybe try the latest one from github

**Comment by hugowinkfield** [comment]
I have reinstalled the latest version from github last week.

Thanks for your help though, I hadn't seen the Method paper you shared with
me before and it has been very useful. I have increased the number of soil
layers to 4.

Luckily there is the apsimx_replace_soil_profile function which allows me
to work around it!




Kind regards
Hugo

**Comment by femiguez** [comment]
@hugowinkfield This was indeed a bug and I think I just fixed it. Part of the issue is that some things in APSIM are constantly changing and I have to keep up those changes. Thanks!
