### ISSUE TITLE
Modeling the Impact of Water and Nitrogen Stress on Maize Phenology Using APSIMX

### ISSUE THREAD

**Issue by lyfranki** [femiguez/apsimx#118]
Hello Dr. Fernando Ezequiel Miguez,

1. I'm currently simulating maize phenology using APSIMX and I'm unsure if the Maize.Leaf.Fw variable represents water stress. Could you please confirm if this is the case?
2. While analyzing my simulation results, I observed that Maize.Leaf.Fw values were sometimes below 1. However, it did not appear to affect thermal time accumulation or the duration between corresponding phenology stages. Can you provide any insights on why this might be the case? Maybe I did something wrong.
3. I'm interested in understanding how APSIMX considers water stress and nitrogen levels when simulating maize phenology. While APSIM accounts for these factors as shown following, I have not been able to locate the relevant code in APSIMX. Could you please confirm if APSIMX incorporates these factors in a similar manner, and if so, provide any guidance on where I can find this information? Generally, the APSIMX inherit all the module in the APSIM Classif, right?

![image](https://user-images.githubusercontent.com/59980694/227409848-99bc525b-54b4-4d9d-bf05-cc76b6b5b0c9.png)
(https://github.com/APSIMInitiative/APSIMClassic/blob/27396788a2c0fcc2750b72700d7fccf35fc7c7ea/Model/Maize/Phenology.cpp#:~:text=double%20Phenology%3A%3AcalcStressesTT(void))

Thanks!
Yin

**Comment by femiguez** [comment]
@lyfranki The issues you are pointing out are known in APSIM. We recently open an issue in github about Nitrogen stress

https://github.com/APSIMInitiative/ApsimX/issues/7839

I see that you posted this here:

https://github.com/APSIMInitiative/ApsimX/issues/7881

I'm hoping you have better luck there, because there is not much I can do about addressing this issue

**Comment by lyfranki** [comment]
> @lyfranki The issues you are pointing out are known in APSIM. We recently open an issue in github about Nitrogen stress
> 
> [APSIMInitiative/ApsimX#7839](https://github.com/APSIMInitiative/ApsimX/issues/7839)
> 
> I see that you posted this here:
> 
> [APSIMInitiative/ApsimX#7881](https://github.com/APSIMInitiative/ApsimX/issues/7881)
> 
> I'm hoping you have better luck there, because there is not much I can do about addressing this issue

Thanks for your reply!

**Comment by lyfranki** [comment]
@femiguez One more question, could we get actual evapotranspiration (ET), potential ET (PET), sw_supply (Daily soil water supply over the profile) and sw_demand (Total crop demand for water) when simulating ApsimX?

**Comment by femiguez** [comment]
You need to look for those in the Report. For example, PET is in [MicroClimate].PetTotal (However, the docs has units of MJ/m2, but this might be wrong and it's actually mm). They are not super easy to find but the soil related variables will be in [Soil].SoilWater.ESW (for extractable soil water)

**Comment by femiguez** [comment]
I'll close this for now. Open a new one if needed
