### ISSUE TITLE
Replacement not found error

### ISSUE THREAD

**Issue by gabrielhintz** [femiguez/apsimx#122]
Hi,

Hope you can help me.

When I try run the optimization,

apsimx::optim_apsimx(file = "CA_5_0_20_21_15Dec.apsimx",
                     src.dir = extd.dir,
                     parm.paths = c(pp1,pp2,pp3,pp4),
                     data = obsRaio,
                     weights = "mean",
                     replacement = c(T,T,T,T),
                     initial.values = c(400,112, 1, 500))

I'm getting this error:

"Error in edit_apsimx_replacement(file = file, src.dir = src.dir, wrt.dir = src.dir, :
Models.Core.Replacements not foundNA not found"

It seems like the Replacements are not in the apsimx file but it is. Attached is the apsimx file.

[2_Cultivars.zip](https://github.com/femiguez/apsimx/files/11443965/2_Cultivars.zip)

**Comment by gabrielhintz** [comment]
Thanks @femiguez, I could solve it with 

root = list("Models.Core.Folder", 1)

but unfortunately got a new one.

Error in xtfrm.data.frame(x) : cannot xtfrm data frames

**Comment by femiguez** [comment]
@gabrielhintz Ok. I'm closing this now
