### ISSUE TITLE
Simulating Maize Development with Varying Nitrogen Dosage on Different Dates

### ISSUE THREAD

**Issue by pathakprecisionag** [femiguez/apsimx#124]
I am interested in simulating maize development in APSIMX, specifically by applying two different dosages of nitrogen on different dates. I am not sure whether using "Fertilise on fixed dates" and "Fertilise on fixed dates (advanced)" together would be good. I would like to know if this could work well or not and I am open for suggestions. 

Additionally, if the above options are not suitable, I would like to explore the possibility of modifying the "operation" file in APSIMX using R, but I am not sure whether we could edit that using R.

I would greatly appreciate any guidance or suggestions on how to approach this simulation scenario. Thank you for your assistance!

**Comment by femiguez** [comment]
@pathakprecisionag It is possible now with the package to edit operations. The other questions are better asked in the APSIM github. I'm closing this
