### ISSUE TITLE
Edit Manager Components of Rotations using the apsimx R package

### ISSUE THREAD

**Issue by smkuhlani** [femiguez/apsimx#133]
We are attempting to edit an apsimx rotation file for varieties and plant population using the apsimx R package. The R package provides an option for editing one manager file. How do i edit the 2 manager rotation options using the apsimx r package file. Each crop in the rotation sequence will be edited separately.  I have attached the r script which is modifying the manger file (for variety and population) for monocrop and the corresponding rotation file (just in case). @Janewanguimugo 

[testrot.zip](https://github.com/femiguez/apsimx/files/12643560/testrot.zip)

**Comment by femiguez** [comment]
We have discussed this over email. I'm closing it. Feel free to open a new issue.
