### ISSUE TITLE
Issues with the get_isric_soil_profile() command

### ISSUE THREAD

**Issue by Janewanguimugo** [femiguez/apsimx#134]
I am trying to download soil data but it comes without the sorghum soil parameterized. How can I edit this code so that my soil has Sorghum?
[sorghum.zip](https://github.com/femiguez/apsimx/files/12682655/sorghum.zip)

#Get soil 
x <- 29.7
y<- -20.9
crop<-  "sorghum.apsimx"
soil <- get_isric_soil_profile(lonlat = c(x,y))

#Replace soil profile

swat <- soilwat_parms()

#We need to add the crop names
soil$crops <- c("Sorghum", "Maize")

edit_apsimx_replace_soil_profile(crop, root = c("pd", "Base_one"), 
                                 soil.profile = soil, 
                                 overwrite = TRUE)

**Comment by femiguez** [comment]
@Janewanguimugo I added an argument to get_isric_soil_profile, which allows for the addition of crops. The call would be:

```
sp1 <- get_isric_soil_profile(lonlat = c(-93, 42), add.args = list(crops = c("Maize", "Sorghum")))
```
However, I can't test this now because the soilgrids REST API is down

**Comment by Janewanguimugo** [comment]
It works perfectly! Thank you
