### ISSUE TITLE
apsim_example

### ISSUE THREAD

**Issue by snehabharadwaj987** [femiguez/apsimx#136]
Hello sir,
I am running an example file, for Millet I can generate the output but for oryza there is some sort of error.
millet <- apsim_example("millet")
summary(millet)
o <- apsim_example("Oryza")
Error in match.arg(example, choices = ex.ch) : 
  'arg' should be one of “agpasture”, “Canopy”, “Centro”, “Millet”, “Potato”, “Sugar”

also i cannot get the output using this code
apsim(file = "Oryza.apsim", simplify = F)

thanks

**Comment by femiguez** [comment]
@snehabharadwaj987 The first message is not an error. It was intentional that I restricted the examples that you can run to only a small subset of the ones available in APSIM Classic. Oryza was not one of them.

I'll look into the second issue

**Comment by snehabharadwaj987** [comment]
thank you for the response
There was some directory issue for this code now it's alright. 
apsim(file = "Oryza.apsim", simplify = F)

**Comment by femiguez** [comment]
I'm closing this, but feel free to open an new issue. Thanks!
