### ISSUE TITLE
inspect_apsimx_replacement not working

### ISSUE THREAD

**Issue by guillemodon** [femiguez/apsimx#137]
Hello
I wanted to apply the inspect_apsimx_replacement function, but I received this message:

_> inspect_apsimx_replacement("Opt.apsimx", src.dir = "C:/Users/54343/Desktop/OPT" ,
+                            node = "Maize", display.available = TRUE)_
**Error in inspect_apsimx_replacement("Opt.apsimx", src.dir = "C:/Users/54343/Desktop/OPT",  : 
  Models.Core.Replacements not foundNA not found**

any suggestions? thank you so much

**Comment by femiguez** [comment]
You have probably found out that you need to use root = 'list('Models.Core.Folder', NA)'
This is because the 'replacements' structure has changed. Unfortunately, they are still making changed to 'Replacements' so it is not a 'stable' feature. :(
