### ISSUE TITLE
Reading apsimx with many simulations

### ISSUE THREAD

**Issue by matteolongo2** [femiguez/apsimx#139]
Hello, I would like to change the Operations to apsimx files which include many simulations. Trying to open the file, I get the error: `Error in manager.node[[1]] : subscript out of bounds`

Here my code:

```
edit_apsimx("fodderbeet_quadr.apsimx", 
            node = "Manager",
            manager.child = "SowingFertiliser",
            root = "quadr_0_l_fodderbeet",
            verbose = TRUE)
```
Thank you

[fodderbeet_quadr.zip](https://github.com/femiguez/apsimx/files/13449280/fodderbeet_quadr.zip)

**Comment by femiguez** [comment]
@matteolongo2 The use of operations has not been very common in Next Gen, but it is a reasonable request to provide an enhancement that would handle these better. You might be able to edit it using 'edit_apsimx_replacement'. This allows you to inspect it at least

```
inspect_apsimx_replacement("fodderbeet_quadr.apsimx",
                          root = "quadr_0_l_fodderbeet",
                          node = "Field",
                          node.child = "Operations",
                          display.available = TRUE)
```
I'll let you know if I come up with a better approach

**Comment by femiguez** [comment]
@matteolongo2 This is something I wanted to add for sometime. I just pushed a commit that allows you to change 'Operations'. With version 2.4.8 from github you can do the following

```

new.action <- '[Wheat].Sow(population:100, cultivar:"Hartog", depth:40, rowSpacing:250)'
new.line <- '1991-11-03 [Wheat].Sow(population:100, cultivar:"Hartog", depth:40, rowSpacing:250)'

edit_apsimx("fodderbeet_quadr.apsimx",
            root = "quadr_0_l_fodderbeet",
            node = "Operations",
            parm = list(18, 'Action'),
            value = new.action)

inspect_apsimx("fodderbeet_quadr-edited.apsimx",
               root = "quadr_0_l_fodderbeet",
               node = "Operations",
               parm = list(18, 'Action'))

edit_apsimx("fodderbeet_quadr-edited.apsimx",
            root = "quadr_0_l_fodderbeet",
            node = "Operations",
            parm = list(18, 'Line'),
            value = new.line,
            overwrite = TRUE)

inspect_apsimx("fodderbeet_quadr-edited.apsimx",
            root = "quadr_0_l_fodderbeet",
            node = "Operations",
            parm = list(18, 'Line'))
```
Notice that I'm changing both 'Action' and 'Line'. These seem redundant information in the json file (they are not both displayed in the GUI). 

Let me know if this works for you. I have not added any testing. Another item to add to the TODO list

**Comment by matteolongo2** [comment]
Now I got it, thank you again. However, trying with multiple dates I get this error:
```
new.date <- c("1981-11-03","1981-11-04")
edit_apsimx("test.apsimx",
            root = "quadr_0_l_fodderbeet",
            node = "Operations",
            parm = list(11:12, 'Date'),
            value = new.date,
            overwrite = TRUE)

Error in `*tmp*`[[parm[[1]]]] : subscript out of bounds
```

**Comment by femiguez** [comment]
@matteolongo2 Thanks for the feedback. I'll test this a bit more and get back to you.

**Comment by femiguez** [comment]
@matteolongo2 I just tested this again and it seems to be working well. However, note that it is tricky. It is very easy to edit the wrong line and you have to remember to edit (potentially) all three: 'Date', 'Action' and 'Line'

**Comment by matteolongo2** [comment]
Thank you @femiguez, I simply hadn't updated the package yet. It does work for me as well. Do you think it will be possbile to have a version able to remove/add lines in the near future?

**Comment by femiguez** [comment]
I consider this a reasonable feature request :)

**Comment by femiguez** [comment]
@matteolongo2 I have added code that can add/remove lines to 'Operations'. I have also added some instructions in the details section. I'll close this now, please open a new issue with you have problems.
