### ISSUE TITLE
Running check

### ISSUE THREAD

**Issue by femiguez** [femiguez/apsimx#144]
The following problems arise when running check

- new simulations do not have the 'InitialWater'. It is now just called 'Water'
- 'InitialN' is also gone and now it is 'NO3', 'NH3' or 'Urea'
- 'MicroClimate' has been moved outside the 'Field', which actually makes sense

**Comment by LenLon** [comment]
Curious thing - if you use `inspect_apsimx()` it shows these as Soil children, but when you try to access them and throws an exception because "NO3" is not part of the predefined parameter set :-D

**Comment by femiguez** [comment]
@LenLon Thanks for the comment. I am aware of this and I will make changes to address it. For less common (or newer) 'inspect' type of tasks you can use either 'inspect_apsimx_replacements' or 'inspect_apsimx_json'.

**Comment by LenLon** [comment]
It is not possible to edit these parameters then, though, correct?

I am getting Initial soil water contents of 400+ mm, (Fractions of > 200%) using the ISRIC soil profiles, so this also ties into the issue of APSIM-X not even encoding that fraction anywhere in the .apsimx file :/

**Comment by femiguez** [comment]
APSIM does have some weird behavior. As you know, all the package allows to do is to change the text in the .apsimx file. If APSIM does weird things later, there is not much I can do about that. It will probably be a while until I can look at this, because I have other priorities. :)

**Comment by LenLon** [comment]
An addendum: Does the function edit_apsimx_replace_soil_profile() still function correctly with the renamed soil parameters?

After using the function, I am seeing different layer structures for the soil water properties and the NO3/NH4/Urea tabs, though I am not sure if that is the GUI or an actual issue with the soil profile:

NO3
![image](https://github.com/femiguez/apsimx/assets/118363045/2f92dcb9-0421-40fa-b670-b19dd9cf82bc)

 Physical
![image](https://github.com/femiguez/apsimx/assets/118363045/877434f8-2e57-41ff-8ead-451ca306e6d0)

**Comment by femiguez** [comment]
@LenLon Sorry for the delay. You have probably figure out by now that the layers in APSIM do not need to agree between Physical and NO3 for example.

Also, I'm closing this as the package seems to be able to handle the changes they have made recently
