### ISSUE TITLE
get_isric_soil_profile() problem

### ISSUE THREAD

**Issue by WangChunhu** [femiguez/apsimx#146]
This is my code:
soil_profile <- NULL
soil_profile <- apsimx::get_isric_soil_profile(lonlat = c(119.41, 32.39))

And the issue is:
Error in open.connection(con, "rb") : 
  cannot open the connection to 'https://rest.isric.org/soilgrids/v2.0/properties/query?lon=114.37&lat=36.12&property=bdod&property=soc&property=phh2o&property=clay&property=sand&property=nitrogen&property=cec&depth=0-5cm&depth=0-30cm&depth=5-15cm&depth=15-30cm&depth=30-60cm&depth=60-100cm&depth=100-200cm&value=mean'
此外: Warning message:
In open.connection(con, "rb") :
  URL 'https://rest.isric.org/soilgrids/v2.0/properties/query?lon=114.37&lat=36.12&property=bdod&property=soc&property=phh2o&property=clay&property=sand&property=nitrogen&property=cec&depth=0-5cm&depth=0-30cm&depth=5-15cm&depth=15-30cm&depth=30-60cm&depth=60-100cm&depth=100-200cm&value=mean': Timeout of 60 seconds was reached

It seems that the website is in trouble.

If you have any time, please check the problem.
Thanks

**Comment by femiguez** [comment]
@WangChunhu The SoilGrids rest service is not always available. I just checked and it is not working for me either. Also, note that there is a limit of approx 5 queries per minute.

**Comment by WangChunhu** [comment]
@femiguez That sounds terrible. Cloud you please make it work as soon as possible at your convenience. I believe many people are waiting for your good news.

**Comment by femiguez** [comment]
@WangChunhu I have no control over that. :) The website: https://rest.isric.org/ is currently down.

**Comment by WangChunhu** [comment]
Oh! Bad luck. Hope it returns to normal soon
