### ISSUE TITLE
error when using get_isric_soil function: Error in !is.na(Thickness) && any(Thickness < 0) :   'length = 6' in coercion to 'logical(1)'

### ISSUE THREAD

**Issue by nelegloy** [femiguez/apsimx#153]
I run this code 
while country_grid is a shapefile for the Niger River Basin with these characteristics: 

> country_grid
Simple feature collection with 869 features and 6 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -11.5079 ymin: 4.5 xmax: 15.56203 ymax: 24.14429
Geodetic CRS:  WGS 84
First 10 features:
   fid Long  Lat  NAME_0 RASTERVALU Names                       geometry
1   83 5.75 4.75 Nigeria       4.75  MUOY POLYGON ((5.5 5, 6 5, 6 4.5...

soil_list <- vector(mode = "list", 
                    length = length(country_grid$centroids)) # initialise list for collecting soil profiles

for (pnt in 1:length(country_grid$centroids)) {        # loop over all centroids
  
  x <- round(country_grid$centroids[pnt][[1]][1], 2)   # save x / lon coordinate of centroid, round to two decimals
  y <- round(country_grid$centroids[pnt][[1]][2], 2)   # save y / lat coordinate of centroid, round to two decimals
  
soil <- get_isric_soil_profile(lonlat = c(x,y), find.location.name = F) 

}

I get either this error :  Grid point , lon 5.75 lat 4.75 : 'length = 6' in coercion to 'logical(1)' 

or this one:  Error in !is.na(Thickness) && any(Thickness < 0) :   'length = 6' in coercion to 'logical(1)'
                                               
                                               
                                               do you have an idea how this can be solved? Thanks a lot !!
                                               My R version is 4.3.3. (4.3.2 same error)

**Comment by femiguez** [comment]
@nelegloy Which version of the package are you using? I think this issue is fixed in the current version on github (apsimx 2.7.52).

**Comment by nelegloy** [comment]
Thank you! that was actually the problem, although I downloaded the package 2 weeks ago the version was 2.6.2 .
