### ISSUE TITLE
Error in get_isric_soil_profile function;   object 'crps' not found

### ISSUE THREAD

**Issue by smkuhlani** [femiguez/apsimx#157]
We are running the function to download the soil for a certain point:

 get_isric_soil_profile(
  lonlat = c(37.62541, -1.78472),
  statistic = c("mean", "Q0.5"),
  find.location.name = TRUE,
  fix = FALSE,
  verbose = TRUE,
  physical = c("default", "SR"),
  xargs = NULL
)

we are getting the error below:

Error in get_isric_soil_profile(lonlat = c(37.62541, -1.78472), statistic = c("mean",  : 
  object 'crps' not found

**Comment by femiguez** [comment]
@smkuhlani Thanks for the report! This is now fixed in github. Also, I suggest looking at function 'get_worldmodeler_soil_profile' and also building a soil profile using apsimx_soil_profile and passing that to the isric function.

**Comment by smkuhlani** [comment]
'get_worldmodeler_soil_profile'  function, initially worked then began to give the error below:

apsimx::get_worldmodeler_soil_profile(lonlat = c(37.26521,-1.52233))

 Warning message:
In get_worldmodeler_soil_profile(lonlat = c(37.26521, -1.52233)) :
  Could not get a soil for row 1

May you please cross check if the error is on my side.
