### ISSUE TITLE
Ability to use the edit_apsimx() function for creating a copy of an .apsimx file with an edit tag

### ISSUE THREAD

**Issue by LenLon** [femiguez/apsimx#165]
Hello,

I got used to using the `edit_apsimx` function to create a copy of an .apsimx file with an edit tag using the `overwrite = F` and `edit.tag` arguments for batching simulations so the individual jobs don't try to access the same .apsimx file.

To my shock this was changed in a recent update, now throwing the error `'value' is missing`. I'm aware I can get around this with base R using `file.copy` and `file.rename`, but I thought it would be a useful use case of the function that could be kept in, as it doesn't run the risk of breaking anything else?

**Comment by femiguez** [comment]
@LenLon If the original behavior has changed it was certainly not my intention. When providing these reports, can you tell me which version of apsimx are you using? It it certainly possible that in the current version in github I have broken some things as I'm trying to fix others. :) :(
