### ISSUE TITLE
Reference the apsimx R Package

### ISSUE THREAD

**Issue by smkuhlani** [femiguez/apsimx#170]
How does one Reference the apsimx R Package?

**Comment by femiguez** [comment]
Thanks for asking! In general, for any R package you can do:

```r
citation(package = "apsimx")
```
It is important to include the version. I'm planning to submit an update to CRAN soon as I have beed fixing many issues.

**Comment by femiguez** [comment]
I'm closing this. Open a new issue if you have anything else to report. Thanks!
