### ISSUE TITLE
Parameter optimization example

### ISSUE THREAD

**Issue by femiguez** [femiguez/apsimx#23]
Coming up is function optim_apsim to optimize parameters for Classic

**Comment by femiguez** [comment]
Need to create a vignette with philosophy and examples

**Comment by ckluss** [comment]
Dear Fernando, 

maybe it is also possible to implement a wrapper like in [1,2] for APSIMX. I'm currently searching and have found your two current packages, which help me a lot. I really like the simple interface of your package and the support of the classic version.

Kind regards
Christof

[1] https://sticsrpacks.github.io/CroptimizR/articles/ApsimX_parameter_estimation_simple_case.html
[2] https://github.com/hol430/ApsimOnR/blob/master/R/apsimx_wrapper.R

**Comment by femiguez** [comment]
Hi Christof, Thanks for your interest! In the newest version of the package (version 1.954) there is a preliminary function 'optim_apsimx' which is very similar (but not identical) to optim_apsim. I have not tested it at all though. However, I would like to also include in the vignette more context. I think there are many "traps" when trying to optimize parameters in crop models. At some point I'll include this philosophy and an example using these tools. If you want to try these tools and provide feedback, that would be great!

**Comment by femiguez** [comment]
I'm currently testing the function. Having some issues, but it seems to be running.

**Comment by femiguez** [comment]
If you are interested take a look at this: https://femiguez.github.io/apsimx-docs/optim-apsim.html

**Comment by femiguez** [comment]
You are welcome. Feel free to report any issues or feedback. Best, Fernando

**Comment by femiguez** [comment]
I'm closing this as this is now in CRAN. Please open a new issue if anything comes up.
