### ISSUE TITLE
Undefined exports: edit_apsimx_batch

### ISSUE THREAD

**Issue by alancho** [femiguez/apsimx#3]
Hi Fernando,

Many thanks for creating this package! I found the following error when trying to install under Debian 10:

> devtools::install_github("femiguez/apsimx", build_vignettes = TRUE, build_opts = c("--no-resave-data", "--no-manual"))

Downloading GitHub repo femiguez/apsimx@master
✔  checking for file ‘/tmp/RtmpWuPIqF/remotes1c5f2c01bd0c/femiguez-apsimx-22e8c3e/DESCRIPTION’
─  preparing ‘apsimx’:
✔  checking DESCRIPTION meta-information
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package ‘apsimx’ ...
   ** using staged installation
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   *** installing help indices
   ** building package indices
   ** installing vignettes
   ** testing if installed package can be loaded from temporary location
   Error: package or namespace load failed for ‘apsimx’ in namespaceExport(ns, exports):
    undefined exports: edit_apsimx_batch
   Error: loading failed
   Execution halted
   ERROR: loading failed
─  removing ‘/tmp/Rtmp53E4PK/Rinst1c7831c72908/apsimx’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'apsimx' from GitHub:
  System command error, exit status: 1, stdout + stderr (last 10 lines):
E> ** installing vignettes
E> ** testing if installed package can be loaded from temporary location
E> Error: package or namespace load failed for ‘apsimx’ in namespaceExport(ns, exports):
E>  undefined exports: edit_apsimx_batch
E> Error: loading failed
E> Execution halted
E> ERROR: loading failed
E> * removing ‘/tmp/Rtmp53E4PK/Rinst1c7831c72908/apsimx’
E>       -----------------------------------
E> ERROR: package installation failed

Perhaps the culprit is line 16 in NAMESPACE, where it is declared:
export(edit_apsimx_batch)

Thanks for your help,

Saludos,

Alan

**Comment by femiguez** [comment]
Hi @alancho ! Yes, that was a temporary bug that should be fixed by now. By the way, that function 'edit_apsimx_batch' is experimental and should not be used yet. I appreciate any feedback. Best, Fernando

**Comment by alancho** [comment]
Thanks, Fernando! Yes, it is solved now. Well done on creating the package. I'll follow its development closely. Cheers, Alan
