### ISSUE TITLE
Error when using apsimx() to run .apsimx files

### ISSUE THREAD

**Issue by ShiruiH** [femiguez/apsimx#31]
Hi Fernando,
Thanks for this package which is very handy! I have used it for a while.
The apsimx() have been working well a year ago but yesterday the error popped up when I tried to run apsimx files with it: 'Error in auto_detect_apsimx() : Could not find APSIM-X in the Windows Registry'. I checked everything I can think of. The Models.exe directory, the apsimx files directory, APSIM-X itself. They all seem good. I am using a self-compiled APSIM-X. And I set the global options using apsimx_options():
```r
apsimx_options(exe.path = 'C:/XXX/YYY/ZZZ/ApsimX/Bin/Models.exe', examples.path = 'C:/XXX/YYY/ZZZ/ApsimX/Examples', warn.versions = TRUE)
sim <- apsimx(file = 'fileName.apsimx', src.dir = 'C:/apsimxFilePath/', value = 'all', cleanup = FALSE)
```
My R version is 4.0.4.
Any suggestion to fix this? Thanks in advance!

**Comment by femiguez** [comment]
Hi ShiruiH! Thanks for your feedback! Which version of the apsimx package are you using? I believe your problem would go away if you install the latest version from github. I'm in the process of submitting a new version to CRAN, so if you want to wait a few days, you can go that route. Best!

**Comment by ShiruiH** [comment]
> Hi ShiruiH! Thanks for your feedback! Which version of the apsimx package are you using? I believe your problem would go away if you install the latest version from github. I'm in the process of submitting a new version to CRAN, so if you want to wait a few days, you can go that route. Best!

Thanks for your prompt reply. It works! I have updated the package using 'devtools' to 1.977. I was using 1.971 previously, guess that is the latest CRAN version. Cheers!

**Comment by ShiruiH** [comment]
Hi Fernando,
Sorry I need to reopen this issue and bother you again since I have encountered another issue when using apsimx() on the High-Performance Computing (HPC) (Linux OS).
Some background info: I don't have admin privilege on the HPC so I compiled the APSIM-X on Windows and copied the list of files into the HPC as suggested in this post https://github.com/APSIMInitiative/ApsimX/issues/3649. It worked well when I used mono to run .apsimx files on it.
For now, I tried to run .apsimx from R. The R script works on Windows. But it showed the error message "Error in auto_detect_apsimx() : object 'apsimx.versions' not found" on Linux. I'm fairly confident that the directory of .exe and example files are correct. And the package has already been updated to 1.977, the R version is 4.0.0. As I looked into https://github.com/femiguez/apsimx/blob/9cbfe043bc7bab3f7dfaea6c7efe62d1137f2920/R/apsimx.R#L88. It seems the error message comes from https://github.com/femiguez/apsimx/blob/9cbfe043bc7bab3f7dfaea6c7efe62d1137f2920/R/apsimx.R#L150
Which is totally understandable since I don't have admin privilege to add anything into the '/usr/local/lib' directory, they should find no apsim files in there.
I'm not quite sure if I understand this right and if I do so, is there any way to solve it? E.g. letting users to define the path where to find the object "apsimx.versions"? Or please let me if I'm wrong and if you have any suggestion to fix this issue. Thanks in advance for your patience.

Shirui

**Comment by femiguez** [comment]
Hi Shirui, I will try to do my best considering that I do not have access to your system. This is my idea: when you install APSIM-X on the HPC system, where is the executable path now? It is not in "/usr/local/lib/apsim" as it would normally be installed. You need to point to it through the use of 'exe.path' in your R script through the use of 'apsimx_options'. Looking at my code, that error message should appear only if APSIM is indeed installed in the HPC, but my code is Debian specific and your HPC system might be a different flavor of Linux. I'd be happy to modify my code, if that's what is needed, but I'm not sure how with the information you have given me.

**Comment by ShiruiH** [comment]
Hi Fernando,
Our HPC system runs on Red Hat.
Technically, the APSIM-X was not directly installed on the HPC system. It was self-compiled on my own PC (Windows) and copied into my working directory on the HPC. Let's say the model directory on the HPC is 'myWorkingDir/ApsimX/'. So the 'exe.path' is 'myWorkingDir/ApsimX/Bin/Models.exe'. I have used 'apsimx_options' to point to it before apsimx() is used:
```r
apsimx_options(exe.path = 'myWorkingDir/ApsimX/Bin/Models.exe', examples.path = 'myWorkingDir/ApsimX/Examples', warn.versions = TRUE)
```
Theoretically, it already knows the exe and examples file path as I pointed to. So I'm also confused about why it failed to find the apsimx.version.

**Comment by femiguez** [comment]
Running all this stuff on an HPC is certainly complex. There are a number of things I would need to know in order to help you.
In R (on the cluster) run the following
`library(apsimx)`
`packageVersion("apsimx")`
`apsimx.options`
`apsimx_options(exe.path = './myWorkingDir/ApsimX/Bin/Models.exe')`
`apsimx:::auto_detect_apsimx()`
Let me know what you get back

**Comment by ShiruiH** [comment]
Thanks.
```r
> packageVersion("apsimx")
1.977
> apsimx.options
<environment: 0x5063df0>
> apsimx_options(exe.path = './myWorkingDir/ApsimX/Bin/Models.exe')
# Nothing returned
> apsimx:::auto_detect_apsimx()
Error in apsimx:::auto_detect_apsimx() : 
  object 'apsimx.versions' not found
In addition: Warning message:
In apsimx:::auto_detect_apsimx() :
  APSIM-X not found, but a custom one is present
```

**Comment by femiguez** [comment]
Can you re-install the package from github and try the previous code again? Basically, I had only tested my code in a Linux machine with Debian with APSIM-X installed. Your case is a bit different, but I'm hoping now it does not throw an error.

I made only a couple of changes to auto_detect_apsimx.

**Comment by ShiruiH** [comment]
Hi Fernando,
They all work now, including the apsimx() function. I really appreciate your time and help!

Cheers,
Shirui

**Comment by femiguez** [comment]
Great! It is possible that you will run into more issues when running R code in HPC because when you spawn processes apsimx environments might not be exported. It might depend on how you set up your parallelization

**Comment by ShiruiH** [comment]
Yes, I'm also concerned about more issues are coming. Anyway, I have three to four plans in mind to arrange the whole workflow and hopefully, I can simplify the process and dodge some potential issues.

**Comment by femiguez** [comment]
@ShiruiH I'm thinking of closing this specific issue. If you run into something different, please open a new issue. Thanks!
