### ISSUE TITLE
Error in apsim Classic No .out file

### ISSUE THREAD

**Issue by gaozitianhaha** [femiguez/apsimx#42]
Hi femiguez,
I meet an issue when using the apsim() to run apsim classic file. When I run using the following code:
apsimx::apsim("Canopy.apsim",src.dir = ".",value = "report",simplify = TRUE)

it says: " cannot open file './Canopy.out': No such file or directory"

I thought the .out and .sum files are available after the running not before, but why it asks to provide these files when running the .apsim file? Sorry I am very new to APSIM so please forgive me if the question is silly..

Best regards,
Zitian

**Comment by femiguez** [comment]
Is there a reason why you are using Classic? If you are new to APSIM you should probably use Next Gen instead.
This code works for me (you need to be in a directory with write permissions):

```
library(apsimx)
ex.dir <- auto_detect_apsim_examples()
file.copy(file.path(ex.dir, "Canopy.apsim"), ".")
canopy <- apsim("Canopy.apsim")
```

**Comment by gaozitianhaha** [comment]
Hi femiguez,
Thank you for your prompt reply and sorry for the late response. I use Classic as previously all files are modified based on xml. Problems solved with your help!

Thanks again.

Best regards,
Zitian

**Comment by femiguez** [comment]
I will close this issue then. Feel free to open a new one if you have other questions or bug reports.
