### ISSUE TITLE
Questions about optim_apsim

### ISSUE THREAD

**Issue by dxl-cde** [femiguez/apsimx#47]
Hello, Fernando！
An error occurred when I ran this code.
this is code :
###############################################################################
library(apsimx)
sim0 <- read.csv(file.path('C:/Users/80770/Desktop/optimi', "dingxi-sim-opt.csv"))
sim0$Date <- as.Date(sim0$Date)

apsim_options(exe.path = "C:/Users/80770/Desktop/optimi/dingxi-opt-ex.apsim")
apsim.options$exe.path
sim0 <- apsim("dingxi-opt-ex.apsim", src.dir = 'C:/Users/80770/Desktop/optimi',
              value = "report")

## Select 
sim0.s <- subset(sim0, 
                 Date > as.Date("2017-03-19") & Date < as.Date("2018-08-01"))

#############################################################################
this is error:
library(apsimx)
> sim0 <- read.csv(file.path('C:/Users/80770/Desktop/optimi', "dingxi-sim-opt.csv"))
> sim0$Date <- as.Date(sim0$Date)
> 
> ## ----sim0-wheat-sim, eval = FALSE---------------------------------------------
> apsim_options(exe.path = "C:/Users/80770/Desktop/optimi/dingxi-opt-ex.apsim")
> apsim.options$exe.path
[1] "C:/Users/80770/Desktop/optimi/dingxi-opt-ex.apsim"
> sim0 <- apsim("dingxi-opt-ex.apsim", src.dir = 'C:/Users/80770/Desktop/optimi',
+               value = "report")
Error in apsim("dingxi-opt-ex.apsim", src.dir = "C:/Users/80770/Desktop/optimi",  : 
  In APSIM Classic you can only run a file from the current directory.
> 
> ## ----sim0-viz-----------------------------------------------------------------
> ## Select 
> sim0.s <- subset(sim0, 
+                  Date > as.Date("2017-03-19") & Date < as.Date("2018-08-01"))
######################################################################
I have only one. APSIM file in the optimi folder，Sincere regards！

**Comment by femiguez** [comment]
I have some questions/comments:

1) When you load the package using *library(apsimx)* do you get any messages? If not, you probably do not need to change the apsim.exe argument in *apsim_options*. To make sure this is fine, run one of the examples first and make sure that it works

```
library(apsimx)
millet <- apsim_example("Millet")
```
2) The message ' In APSIM Classic you can only run a file from the current directory.'  means that you should not change 'src'dir' but rather change in R the working directory to **C:/Users/80770/Desktop/optimi** and then simply run:

```
sim0 <- apsim("dingxi-opt-ex.apsim") 
```
3) The object **sim0** that you read in at first is confusing. If you want to do optimization you should read in data of some type. **sim0** in the example is a *default* simulation. Do you have observed data that you want to compare to APSIM simulations?

**Comment by dxl-cde** [comment]
Thank you very much for your timely advice！yes. I want to get the results of this simulation,so as to optimize the model parameters.Sincere regards！

**Comment by femiguez** [comment]
Do you have other questions? Otherwise, I will close this issue.

**Comment by JF888666** [comment]
HI, @dxl-cde [dxl-cde](https://github.com/dxl-cde), 
I tried running apsim() and it shows that In APSIM Classic you can only run a file from the current directory, how did you solve the problem, I would be grateful if I could get your guidance.

![3](https://user-images.githubusercontent.com/103365891/218673049-3e821f0c-290a-41ca-bcfd-dba878f80a4b.png)
