### ISSUE TITLE
editing apsimx rotation files

### ISSUE THREAD

**Issue by tuliscot** [femiguez/apsimx#62]
Hallo APSIMers,

I am editing the soil and fertilizer components of example apsim rotation file (MaizeSoybean.apsimx). I would like to edit both maize and soybean components.  I know i am supposed to specify the soil and fertilizer children names/root node label but i am unsure of how to arrange the children names to make the edits.  In my attempts, i am getting the following error:

Simulation structure: 
list Name: Simulations 
list length: 9 
list names: $type ExplorerWidth Version ApsimVersion Name Children IncludeInDocumentation Enabled ReadOnly 
Children: Yes 
Children length: 4 
Children Names: Replacements SimulationSoybean SimulationMaize DataStore 
Error in edit_apsimx("MaizeSoybean.apsimx", src.dir = extd.dir, wrt.dir = path,  : 
  more than one simulation found and no root node label has been specified 
 select one of the children names above

I have attached the script, with the simulation.

Cheers

Tuliscot
[notworking_rotation.txt](https://github.com/femiguez/apsimx/files/7341046/notworking_rotation.txt)

**Comment by femiguez** [comment]
I'm closing this. Let me know if you have any issues still
