### ISSUE TITLE
Morris SA on parameter with multi layer values

### ISSUE THREAD

**Issue by andynen** [femiguez/apsimx#85]
Hello there, 

I am interested in using Morris SA on parameter with multi layer values. The demo document only shows for single parameter values. 

Can you please help with how to do that for parameter with multi layer values? 

Thank you,
A

**Comment by andynen** [comment]
@femiguez thank you for your reply - This helps me to understand how to deal with multilayer parameters - a local SA may be more appropriate. 

I do not have a working example yet - I was following the vignette and wanted to test that option. 

Thank you, 
A

**Comment by femiguez** [comment]
@andynen I'm closing this, but feel free to open another issue if you have questions
