### ISSUE TITLE
Run APSIM Classic Files Using The APSIMX R Package scripts?

### ISSUE THREAD

**Issue by smkuhlani** [femiguez/apsimx#93]
Hallo APSIMers,

Can i run APSIM Classic files using the APSIMX R package scripts?
I am hesitant to invest time recalibrating APSIM X from scratch yet i have done that before for APSIM Classic.

Thanks

**Comment by femiguez** [comment]
Hi @smkuhlani, I'm not sure what your are trying to do, but the package supports both Classic and Next Gen. There are some minor differences, but in general functions which contain 'apsim' are for Classic and those that contain 'apsimx' are for Next Gen. Let me know if you have questions.

**Comment by femiguez** [comment]
I'm closing this. Please open a new issue if you have another question
