### ISSUE TITLE
Customized Report is not reported in the variable output

### ISSUE THREAD

**Issue by andynen** [femiguez/apsimx#97]
Hello @fermiguez, 

I am testing a maize simulation using APSIMX. I have customized the variables I want from the report, however it is the default variables that are reported. I am using the following R tasks and attached simulation file. 

file_name = "Maize.apsimx"
apsim_output = apsimx( file_name, src.dir = out_dir2, value = "user-defined", silent = T, cleanup = T)

Your help will be greatly appreciated. 
Thank you!

[Maize.zip](https://github.com/femiguez/apsimx/files/9237857/Maize.zip)

**Comment by femiguez** [comment]
@andynen The "user-defined" option means that there might be multiple table reports in the simulation database and you might want to only bring one of those into your data frame. In the 'Maize.apsimx' simulation there is only one report called 'Report' so there is no need to specify anything for the 'value' argument. The function 'apsimx' will automatically pick it as the table to bring into R as a data frame.

**Comment by femiguez** [comment]
I'm closing this. If you still have questions, open a new one, please.
