### ISSUE TITLE
Get NASA-POWER data for an APSIM met file

### ISSUE THREAD

**Issue by YanZongzheng** [femiguez/apsimx#98]
Hi @femiguez ,
Recently, I am working on running APSIM next generation with apsimx. When I extract the NasaPower data with get_power_apsim_met function, it gives the wrong AMP parameters in met file. Can you please check get_power_apsim_met, to avoid the error.

**Comment by femiguez** [comment]
Hi @YanZongzheng! Can you show me an example of what you get with 'get_power_apsim_met', why it is wrong and what do you expect to get? Thanks!

**Comment by femiguez** [comment]
This has been addressed. If you want to try it out, let me know how it goes

**Comment by YanZongzheng** [comment]
Hi @femiguez,
It's still the wrong amp

**Comment by femiguez** [comment]
@YanZongzheng Can you provide an example? Let me know what you get and what do you think should be the correct answer.
Also, how does this affect APSIM simulations?

**Comment by femiguez** [comment]
Please provide an example. Otherwise, I will close it.

**Comment by femiguez** [comment]
Open a new issue with an example please
