### ISSUE TITLE
Can not open the file Wheat-opt-ex.apsimx again, after runing with APSIM 2022.8.7.071

### ISSUE THREAD

**Issue by YanZongzheng** [femiguez/apsimx#99]
I runed the Wheat-opt-ex.apsimx, and then closed it, when i open it again, the  APSIM 2022.8.7.071 version showed below error.
Error reading file D:\Rlibrary\apsimx\extdata\Wheat-opt-ex.apsimx --> Error setting value to 'Lines' on 'Models.PMF.Cultivar'. --> Value cannot be null. (Parameter 'source')

**Comment by femiguez** [comment]
It is possible that the file was corrupted during the optimization process. If you are trying to reproduce the example, you should copy the files to a different folder.

**Comment by femiguez** [comment]
I am closing this unless you have another question
